:docinfo:
= pdmDocuments
Documentation

PDMDocuments ist ein Infosystem, welches über eine Rest-Api auf das PDM-System zugreift und 
die mit dem Artikel verknüpften Dokumente abholt und anzeigt.
Das Infosystem ist durch ein Layout in den Druckprozess eingebunden und druckt zu einem Beleg die freigegeben Zeichnungen.

Derzeit ist der Zugriff auf die folgenden PDM-System implementiert :
 
- Keytech +
- ProFile +
- SolidWorksPDM (Lösung von dem SolidWorks-Partner Coffee) +    

== Technische Vorraussetzungen
abas: 

Um die Lizenzprüfung für PDMDocuments ausführen zu können muss das AddOn Cloud-Connect installiert sein bevor die Installation gestartet werden kann.
Unter dem folgenden Link findet man die Installationsanleitung für Cloud-Connect: +
 
https://documentation.abas.cloud/en/cloud-connect/

Keytech:
Es muss die Keytech-RestAPI auf dem Server von Keytech installiert sein.

Für den Zugriff benötigen wir einen Benutzer in Keytech,
welcher nur Zugriffsrechte für die Dokumente hat, welche in PDMDocuments angeschaut werden sollen.  


ProFile:

Es muss der ProFile APP Server installiert sein.

Für den Zugriff benötigen wir einen Benutzer in ProFile,
welcher nur Zugriffsrechte für die Dokumente hat, welche in PDMDocuments angeschaut werden sollen.  

SolidWorks:
Die RestAPI von Coffee muss installiert sein.



== Installation
PDMDocuments wird mit dem abas-esdk-Installer installiert.

pdm-<Version>.jar 

Es wird das Infosystem PDMDOCUMENTS, das Layout PDMDOCUMENTS, 
Aufrufparameter und die entsprechenden Programme installiert.  

=== Nacharbeiten

Die Aufrufparameter zum Aufrufen des Infosystem aus den Masken:

Maske 2 Artikel     : PDMDOCUMENTSTEIL
Maske 42 Bestellung : PDMDOCUMENTSEK
Infosystem APAPIER  : PDMDOCUMENTSAPAPIER
Infosystem PRODLIST : PDMDOCUMENTSPRODLIST


Einbinden des Layouts PDMDOCUMENT in die individuellen Drucklayouts.

== Anpassungen 
Über den Berichtsfuss(bfuss) kann ein FOP eingefügt werden. 



== Konfiguration  

include::profile.adoc[]

include::keytech.adoc[]

include::coffee.adoc[]


include::additionalpage.adoc[]

:nofooter:
== Partner  
Unser PDM-Partner : 

http://www.procad.de

http://www.keytech.de

http://www.coffee.de

== About

pdmDocuments +
(C) abas Software GmbH

https://www.abas-erp.com/
